---
name: Buildozer Env

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: {}

jobs:

  dev:
    name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - uses: WSQS/action-debug-vscode@main


